# each line must have the name (alphanumerical only) followed by the
# url.  everything else is ignore (like these comments) the
# match/ignore filtering are regexp. They are interpolated literally,
# with m/$value/i The matching is done against the resulting filename
# (taken from the title + date prefix)

PlanetBlue:
  url: 'http://www.rts.ch/couleur3/programmes/la-planete-bleue/podcast/?flux=rss'

HeadPhoneCommute:
  url: 'http://reviews.headphonecommute.com/feed/'

SpaceMusicNL7:
  url: 'http://spacemusic.nl/podcast/spacemusic/season7/space7.xml'
  filter:
    match: 'space.*music'
    ignore: 'fresh.*air'
