# each line must have the name (alphanumerical only) followed by the url.
# everything else is ignore (like these comments)

PlanetBlue:
  url: 'http://www.rts.ch/couleur3/programmes/la-planete-bleue/podcast/?flux=rss'

HeadPhoneCommute:
  url: 'http://reviews.headphonecommute.com/feed/'

SpaceMusicNL6:
  url: 'http://spacemusic.nl/podcast/spacemusic/season6/space6.xml'
  filter: 'space.*music'
